name: Auto Tag e Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para calcular o histórico de versões

      - name: Calcular Próxima Versão e Criar Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          # É NECESSÁRIO usar um Personal Access Token (PAT) com permissão de 'repo'.
          # O GITHUB_TOKEN padrão não pode disparar outros workflows (como o de build).
          # Crie um PAT e adicione-o aos Segredos do repositório com o nome 'PAT'.
          github_token: ${{ secrets.PAT }}
          default_bump: patch
          release_branches: main
          tag_prefix: v
          create_annotated_tag: true